"""Update masjid model with area_name and prayer times

Revision ID: e3ae886fa904
Revises: 
Create Date: 2025-12-28 18:43:02.690165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3ae886fa904'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    op.add_column('masjids', sa.Column('area_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('masjids', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('masjids', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('masjids', sa.Column('fajr_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('masjids', sa.Column('dhuhr_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('masjids', sa.Column('asr_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('masjids', sa.Column('maghrib_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('masjids', sa.Column('isha_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('masjids', sa.Column('jummah_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Copy data from area to area_name
    op.execute("UPDATE masjids SET area_name = COALESCE(area, 'Unknown')")

    # Set default prayer times for existing records (Karachi times)
    op.execute("UPDATE masjids SET fajr_time = '05:30' WHERE fajr_time IS NULL")
    op.execute("UPDATE masjids SET dhuhr_time = '13:00' WHERE dhuhr_time IS NULL")
    op.execute("UPDATE masjids SET asr_time = '16:30' WHERE asr_time IS NULL")
    op.execute("UPDATE masjids SET maghrib_time = '18:15' WHERE maghrib_time IS NULL")
    op.execute("UPDATE masjids SET isha_time = '19:45' WHERE isha_time IS NULL")

    # Now make the required columns NOT NULL
    op.alter_column('masjids', 'area_name', nullable=False)
    op.alter_column('masjids', 'fajr_time', nullable=False)
    op.alter_column('masjids', 'dhuhr_time', nullable=False)
    op.alter_column('masjids', 'asr_time', nullable=False)
    op.alter_column('masjids', 'maghrib_time', nullable=False)
    op.alter_column('masjids', 'isha_time', nullable=False)

    # Create index on area_name
    op.create_index(op.f('ix_masjids_area_name'), 'masjids', ['area_name'], unique=False)

    # Drop old columns
    op.drop_column('masjids', 'area')
    op.drop_column('masjids', 'facilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masjids', sa.Column('facilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('masjids', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_masjids_area_name'), table_name='masjids')
    op.drop_column('masjids', 'jummah_time')
    op.drop_column('masjids', 'isha_time')
    op.drop_column('masjids', 'maghrib_time')
    op.drop_column('masjids', 'asr_time')
    op.drop_column('masjids', 'dhuhr_time')
    op.drop_column('masjids', 'fajr_time')
    op.drop_column('masjids', 'longitude')
    op.drop_column('masjids', 'latitude')
    op.drop_column('masjids', 'area_name')
    # ### end Alembic commands ###
