"""Add Phase III columns to models

Revision ID: 9da93c6fccaa
Revises: e3ae886fa904
Create Date: 2025-12-30 00:34:46.091804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9da93c6fccaa'
down_revision: Union[str, None] = 'e3ae886fa904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spiritual_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('spiritual_tasks', sa.Column('minutes_before_prayer', sa.Integer(), nullable=True))
    op.add_column('spiritual_tasks', sa.Column('linked_prayer', sa.Enum('FAJR', 'DHUHR', 'ASR', 'MAGHRIB', 'ISHA', 'JUMMAH', name='linkedprayer'), nullable=True))
    op.add_column('spiritual_tasks', sa.Column('recurrence_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_spiritual_tasks_user_id'), 'spiritual_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spiritual_tasks_user_id'), table_name='spiritual_tasks')
    op.drop_column('spiritual_tasks', 'recurrence_pattern')
    op.drop_column('spiritual_tasks', 'linked_prayer')
    op.drop_column('spiritual_tasks', 'minutes_before_prayer')
    op.drop_column('spiritual_tasks', 'user_id')
    # ### end Alembic commands ###
